- Dockerfile.notebook
- examples/pulsar/docker-compose.yml
Updated the docker image to be in the `kaskada` repo so updated the compose accordingaly
> Update pulsar docker compose with new image

- crates/sparrow-main/src/serve/file_service.rs
- crates/sparrow-main/src/serve/preparation_service.rs
Explicitly closes the temp file, which should(tm) ensure that the temporary file is not eligible for deletion until that happens.
> fix: fix temp file deletion

- docs-src/modules/getting-started/pages/hello-world-cli.adoc
Updated instructions to use a version for which we have a CLI binary available.
> (docs): update cli install instaructions

- docs-src/modules/ROOT/nav.adoc
- examples/Kaskada with CSV.ipynb
- examples/ML_example.ipynb
- examples/Public Demo Examples.ipynb
- examples/Table Pulsar Source.ipynb
This also makes some minor fixes to the notebooks to reflect the fact that the project has been released publicly.
> Add an "examples" section to the docs with links to our notebooks

- docs-src/modules/getting-started/pages/hello-world-cli.adoc
Adds the full path to the downloaded parquet file when calling the cli (#202)
> (docs): Update hello-world-cli.adoc

- clients/cli/api/api.go
related to https://github.com/kaskada-ai/kaskada/issues/202#issuecomment-1497525872
> changed client-id log line to debug-level

- clients/python/src/kaskada/client.py
- docs-src/modules/ROOT/pages/installing.adoc
- docs-src/modules/ROOT/pages/loading-data.adoc
- docs-src/modules/getting-started/pages/hello-world-cli.adoc
- docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
Bash has prettier formatting than shell.
> Use the correct path syntax and highlight with bash

- .github/workflows/ci_client_cli.yml
- .github/workflows/ci_client_python.yml
- .github/workflows/ci_engine.yml
- .github/workflows/ci_proto.yml
- .github/workflows/release_engine.yml
- .github/workflows/release_python_client.yml
- .github/workflows/reusable_ci_arm64_release.yml
- .github/workflows/reusable_ci_wren.yml
- Makefile
- clients/python/src/fenlmagic/__init__.py
- clients/python/src/kaskada/formatters_helpers.py
- clients/python/src/kaskada/formatters_shared.py
- clients/python/src/kaskada/materialization.py
- clients/python/src/kaskada/query.py
- clients/python/src/kaskada/table.py
- clients/python/src/kaskada/utils.py
- clients/python/src/kaskada/view.py
- proto/buf.gen.yaml
- wren/README.md
> updated buf and plugins

- docs-src/modules/getting-started/pages/index.adoc
The goal here is to quickly introduce the concepts needed to understand Kaskada, and provide links to deeper reading as appropriate.
> Rewrite the "getting started" page

- .github/workflows/ci_engine.yml
- Makefile
- tests/integration/shared/helpers/helpers.go
Takes care of the first task in #232
> (ci) adds S3 integration tests

- docs-src/modules/troubleshooting/pages/logs.adoc
Documentation updates for #304.
> Update Log Output Files Documentation (#274)

- README.md
Also, reword to be more encouraging.
> Change README to point at Slack rather than GH Discussions.

- docs-src/modules/getting-started/pages/hello-world-cli.adoc
Updates the hello world cli to use the correct echo path command.
> docs: cli echo path fix

- docs-src/modules/ROOT/pages/loading-data.adoc
- docs-src/modules/developing/pages/tables.adoc
- docs-src/modules/getting-started/pages/hello-world-cli.adoc
- docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
> updated cli getting started docs

- clients/python/src/fenlmagic/__init__.py
> feat: add fenlmagic extension loaded message (#305)

- wren/service/query_v1.go
updates the query path to not set the dataToken to the response if it doesn't exist.  It will only not exist on a brand new system, where no data has been loaded into Kaskada.
After skipping setting the dataToken field, the code correctly returns the failed compilation instead, including helpful fenl diagnostics.
Old Behavior:
```
> ./kaskada_cli table list
(empty set)
> ./kaskada_cli query run Purchase
9:01PM FTL  error="rpc error: code = NotFound desc = data_token not found"
```
New Behavior:
```
> ./kaskada_cli query run Purchase
state: STATE_FAILURE
config: {}
analysis: {}
fenlDiagnostics:
fenlDiagnostics:
- severity: SEVERITY_ERROR
code: E0006
message: Unbound reference
formatted: |+
error[E0006]: Unbound reference
--> Query:1:1
|
1 | Purchase
| ^^^^^^^^ No reference named 'Purchase' …
```
> ignore no dataToken error

- docs-src/modules/ROOT/pages/loading-data.adoc
Adds loading data to the docs.
> docs: Add GCP Configuration to Loading Data

- docs-src/modules/ROOT/pages/installing.adoc
- docs-src/modules/developing/nav.adoc
> docs: update to include readthedocs for clients

- clients/python/src/fenlmagic/__init__.py
- clients/python/src/kaskada/api/remote_session/__init__.py
- clients/python/src/kaskada/api/session.py
- clients/python/src/kaskada/client.py
- docs-src/modules/tools-and-resources/nav.adoc
- docs-src/modules/tools-and-resources/pages/remote-session.adoc
Updates the python client to support a remote session and adds the docs to configure it.
> feat: Remote Session Improvements (python)

- crates/sparrow-runtime/src/metadata/raw_metadata.rs
- crates/sparrow-runtime/src/prepare.rs
- crates/sparrow-runtime/src/read/stream_reader.rs
- crates/sparrow-runtime/src/streams/pulsar/stream.rs
Reverts kaskada-ai/kaskada#426
> Revert "Remove Publish Time from non-prepare Pulsar Paths"

- wren/internal/materialization_client.go
- wren/main.go
also fixes wren hanging after ctrl+c.
> fixed ReconcileMaterializations panic

- crates/sparrow-runtime/src/metadata/raw_metadata.rs
- crates/sparrow-runtime/src/prepare.rs
- crates/sparrow-runtime/src/read/stream_reader.rs
- crates/sparrow-runtime/src/streams/pulsar/stream.rs
PR with the progress made towards debugging the streaming implementation.
Changes:
* Reverted the revert for Publish Time. The implementation was correct, just missing one more step.
* Added the missing step for publish time. When reading the stream, a flag is passed to consider adding the publish time. 
* In the execution phase, no publish time (false).
* In the preparation phase, publish time (true).
> Update Streaming Avro Record Output

- CONTRIBUTING.md
> rectified <a> tag for Development text in CONTRIBUTING.md file

- Makefile
- proto/kaskada/kaskada/v1alpha/table_service.proto
- tests/integration/api/mat_pulsar_to_obj_store_test.go
- tests/integration/api/mat_pulsar_to_pulsar_test.go
- tests/integration/api/queries_v1_test.go
- tests/integration/api/query_v1_errors_test.go
- tests/integration/api/query_v1_test.go
- tests/integration/api/tables_test.go
- tests/integration/shared/go.sum
- tests/integration/shared/helpers/helpers.go
- wren/client/interface.go
- wren/client/object_store_client.go
- wren/compute/compile_manager.go
- wren/compute/prepare_manager.go
- wren/customerrors/customerrors.go
- wren/main.go
- wren/service/query_v1.go
- wren/service/table.go
New option `copy_to_filesystem` added to revert to the old behavior.  @kevinjnguyen we will need to add this option to the python client too.
> changed default behavior of file-load to leave files in-place

- Dockerfile
- Dockerfile.go_cross_amd64_to_arm64
- Makefile
- tests/integration/api/api_suite_test.go
- tests/integration/api/graceful_shutdown_test.go
- tests/integration/api/mat_pulsar_to_obj_store_test.go
- tests/integration/api/mat_pulsar_to_pulsar_test.go
- tests/integration/api/mat_table_to_pulsar_test.go
- tests/integration/api/materializations_test.go
- tests/integration/api/queries_v1_test.go
- tests/integration/api/query_v1_csv_test.go
- tests/integration/api/query_v1_incremental_test.go
- tests/integration/api/query_v1_rest_test.go
- tests/integration/api/views_test.go
- wren/client/object_store_client.go
resolves #474
progress on #473, #459
> improved reliability of integration tests

- crates/sparrow-api/src/kaskada/v1alpha/schema_traits.rs
- crates/sparrow-compiler/src/functions.rs
- crates/sparrow-compiler/src/functions/collection.rs
- crates/sparrow-compiler/src/types/inference.rs
- crates/sparrow-instructions/src/evaluators.rs
- crates/sparrow-main/tests/e2e/collection_tests.rs
- crates/sparrow-main/tests/e2e/main.rs
- crates/sparrow-physical/src/step.rs
- crates/sparrow-plan/src/inst.rs
- crates/sparrow-runtime/src/execute/operation/lookup_request.rs
- crates/sparrow-syntax/src/parser/grammar.lalrpop
- crates/sparrow-syntax/src/syntax/fenl_type.rs
- crates/sparrow-syntax/src/syntax/signature.rs
- proto/kaskada/kaskada/v1alpha/schema.proto
Adds type inference for map types. Does not yet implement any functions for maps.
> feat: support type inference for map<k,v>

- docs-src/modules/ROOT/pages/installing.adoc
- docs-src/modules/getting-started/pages/hello-world-cli.adoc
- install/install.sh
* moves the commands into `install/install.sh` file 
* updates installation instructions in our docs
> docs(install) updates instructions for installation

- wren/client/object_store_client.go
> fixed gcs file loading and query

- .github/workflows/release_engine.yml
- .github/workflows/release_python_client.yml
Adds a beta GitHub release flow. 
The beta release does not have any comments on the release page for now.
> adds beta release ci flow

- .github/workflows/release_python_client.yml
[Resulting release](https://github.com/kaskada-ai/kaskada/releases/tag/python%40v0.5.0-beta.1)
> Python client beta release 

- clients/python/pyproject.toml
Bump minor version for the Python release.
> Python 0.5.1 Version Bump

- Cargo.lock
- crates/sparrow-arrow/Cargo.toml
- crates/sparrow-arrow/src/serde.rs
Also adds tests for `ArrayRef` and `MapArray` serialization.
> feat: Add serde support for arrays

- crates/sparrow-runtime/src/execute/operation/spread.rs
Fixes spots in string spread that weren't generic
> bug: fix non-generic conversions in string spread 

- tests/integration/api/queries_v1_test.go
- tests/integration/api/query_v1_panic_test.go
- wren/service/query_v1.go
Added test reproducing the issue described in #551.  Found that PR #448 probably introduced the bug that causes this issue.  Updated the code to fix the problem.
> fix wren panic on failed complication

- examples/OpenAI.ipynb
- examples/slackbot/Notebook.ipynb
- examples/slackbot/OpenAI.ipynb
Adds an OpenAI Example Notebook
* Reactions?
> feat: OpenAI Example Notebook

- crates/sparrow-compiler/src/frontend/resolve_arguments.rs
- crates/sparrow-compiler/src/functions/aggregation.rs
- crates/sparrow-compiler/src/functions/function.rs
- crates/sparrow-main/tests/e2e/collect_tests.rs
- crates/sparrow-plan/src/inst.rs
and removes unnecessary split in `inst.rs` signatures.
> bug: correctly type-check user facing aggregation signatures

- sparrow-py/pysrc/sparrow_py/__init__.py
- sparrow-py/pysrc/sparrow_py/_timestream.py
- sparrow-py/pysrc/sparrow_py/windows.py
- sparrow-py/pytests/aggregation_test.py
- sparrow-py/pytests/collect_test.py
This also does the package reworking so that `kt.windows.Since` is the since window (rather than `kt.SinceWindow`).
> feat: Add the trailing window

- sparrow-py/docs/.gitignore
- sparrow-py/docs/source/_templates/autosummary/class.rst
- sparrow-py/docs/source/conf.py
- sparrow-py/docs/source/index.md
- sparrow-py/docs/source/reference/results.md
- sparrow-py/docs/source/reference/sources.md
- sparrow-py/docs/source/reference/timestream/aggregation.md
- sparrow-py/docs/source/reference/timestream/arithmetic.md
- sparrow-py/docs/source/reference/timestream/collection.md
- sparrow-py/docs/source/reference/timestream/comparison.md
- sparrow-py/docs/source/reference/timestream/execution.md
- sparrow-py/docs/source/reference/timestream/grouping.md
- sparrow-py/docs/source/reference/timestream/index.md
- sparrow-py/docs/source/reference/timestream/misc.md
- sparrow-py/docs/source/reference/timestream/records.md
- sparrow-py/docs/source/reference/timestream/time.md
- sparrow-py/docs/source/reference/windows.md
- sparrow-py/noxfile.py
- sparrow-py/poetry.lock
- sparrow-py/pyproject.toml
- sparrow-py/pysrc/sparrow_py/_timestream.py
Tweak wording on a few pages.
Make sure all the methods are documented.
Use poetry groups for dependencies in noxfile.
> docs: Update existing docs

- python/docs/source/reference/timestream/misc.md
- python/pysrc/kaskada/_timestream.py
- python/pytests/conftest.py
- python/pytests/else_test.py
- python/pytests/golden/else_test/test_else_.jsonl
- python/pytests/golden/null_test/test_is_null.jsonl
- python/pytests/pandas_source_test.py
> feat: add else call

- python/Cargo.lock
- python/docs/source/guide/aggregation.md
- python/docs/source/guide/sources.md
- python/docs/source/guide/timestreams.md
- python/docs/source/reference/timestream/aggregation.md
- python/docs/source/reference/timestream/collection.md
- python/pysrc/kaskada/plot.py
> docs: Start fleshing out documentation on timestreams

- python/docs/source/blog/index.md
- python/docs/source/blog/posts/2023-03-28-announcing-kaskada-oss.md
- python/docs/source/blog/posts/2023-08-25-new-kaskada.md
- python/docs/source/conf.py
1. Fix the dates so they show up in the right order
2. Include the blog sidebar on posts (it has information about the date, author, etc.)
> docs: Minor fixes to blogs

- Cargo.lock
- crates/sparrow-arrow/src/batch.rs
- crates/sparrow-transforms/Cargo.toml
- crates/sparrow-transforms/src/lib.rs
- crates/sparrow-transforms/src/select.rs
- crates/sparrow-transforms/src/transform.rs
- crates/sparrow-transforms/src/transform_pipeline.rs
Adds the `select` transform to the expressions package
> feat: add select transform

- Cargo.lock
- crates/sparrow-sources/Cargo.toml
- crates/sparrow-sources/src/in_memory.rs
Adds a few unit tests for the in-mem batch.
> test: add in-memory batch unit tests

- python/docs/examples/reddit.qmd
> updated reddit example for quarto

- .github/workflows/ci_python.yml
- python/docs/_extensions/README.md
- python/docs/_scripts/README.md
> added READMEs and simplified CI
